# Generated by Django 2.0.1 on 2018-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsid', models.IntegerField()),
                ('title', models.CharField(max_length=9000)),
                ('author', models.CharField(max_length=1000)),
                ('pubdate', models.DateTimeField()),
                ('headpic', models.ImageField(upload_to='')),
                ('content', models.TextField()),
            ],
        ),
    ]
