# Generated by Django 2.0.2 on 2018-02-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20180128_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headpic',
            field=models.ImageField(upload_to=''),
        ),
    ]
