# Generated by Django 2.0.2 on 2018-02-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20180203_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='newsid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.FileField(upload_to='Upload_Files'),
        ),
    ]
