# Generated by Django 2.0.2 on 2018-02-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_auto_20180205_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='newsid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
